// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozwbwhifotdycxlozxew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96d2J3aGlmb3RkeWN4bG96eGV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNjE1NjQsImV4cCI6MjA2MDkzNzU2NH0.giyH6keHDzQwwxdrRtBbkV9VZT3JxywcrjPt1cMDEP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);